# Tomcat
server:
  tomcat:
    max-threads: 10
    min-spare-threads: 10
  port: 8080

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/devops?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASS:123456}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

